### ISSUE TITLE
Allow web users to choose Popover trigger

### ISSUE THREAD

**Issue by corysimmons** [alantoa/universal-tooltip#2]
https://github.com/alantoa/universal-tooltip/blob/18a3dce08aab542216deb43fe158b54f1cca8b79/src/universal-tooltip.web.tsx#L16-L21

It seems like all web users get the Tooltip trigger.

But then this code in the README seems like you can change the behavior of web:

![image](https://user-images.githubusercontent.com/224636/219700693-b92b3d12-562c-4059-8147-e1c558ba9b83.png)

Is it possible to have web support Popover trigger rather than Tooltip trigger?

**Comment by nandorojo** [comment]
I was going to commend the same thing. The current implementation also breaks SSR hydration since it conditionally toggles tooltip vs popover. Instead, it should be a flag to prevent hydration mismatches, as well as letting users wrap buttons with tooltips without interrupting touches.

**Comment by alantoa** [comment]
no, because this basically is a Tooltip component rather than a Popover component, maybe I remove the Popover component from the web later, just using a  Tooltip component, `Popover` is used here because Tooltip is not supported by the mobile web that's sucks. you can see [this](https://github.com/alantoa/universal-tooltip/issues/3).
